'use client';

import { ChangeEvent, useEffect, useMemo, useRef, useState } from 'react';

type Usage = { month:string; start:string; end:string; lighting:number; power:number; actual:number };
type Rates = {
  updatedAt:string;
  variable:{ month:string; tepcoFuel:number|null; enepalFuel:number|null; enepalProcurement:number|null; support:number|null; renewable:number|null; status:string; sources:string[] }[];
  fixed:{ start:string; company:'TEPCO'|'エネパル'; lightBase:number; tiers:number[]; powerKw:number; powerBase:number; powerSummer:number; powerOther:number; stabilityLight:number; stabilityPower:number; plan:string; source:string }[];
};

const initialRates: Rates = {
  updatedAt:'2026-08-24',
  variable:[{month:'2026-09',tepcoFuel:-10.96,enepalFuel:0,enepalProcurement:null,support:-4.5,renewable:4.18,status:'エネパル調達単価待ち',sources:['https://www.tepco.co.jp/ep/private/fuelcost2/new/index-j.html','https://enepal.co.jp/palpower-energy/power-procurument/']}],
  fixed:[
    {start:'2026-09',company:'TEPCO',lightBase:1870.5,tiers:[29.8,36.4,40.49],powerKw:4,powerBase:1098.05,powerSummer:27.14,powerOther:25.57,stabilityLight:0,stabilityPower:0,plan:'従量電灯B 60A ＋ 低圧電力 4kW',source:'https://www.tepco.co.jp/ep/private/plan/chargelist01.html'},
    {start:'2026-09',company:'エネパル',lightBase:1716,tiers:[19.88,26.48,29.5],powerKw:3,powerBase:1088.34,powerSummer:17.37,powerOther:15.8,stabilityLight:726,stabilityPower:363,plan:'パルプレミアムS B 60A ＋ パル動力プレミアムS 3kW',source:'https://enepal.co.jp/palpower-energy/area-price/kanto/'}
  ]
};
const blankUsage:Usage={month:'2026-09',start:'2026-08-01',end:'2026-08-31',lighting:0,power:0,actual:0};
const yen=new Intl.NumberFormat('ja-JP',{style:'currency',currency:'JPY',maximumFractionDigits:0});
const num=new Intl.NumberFormat('ja-JP',{maximumFractionDigits:1});

function fixedFor(rates:Rates, company:'TEPCO'|'エネパル', month:string){return rates.fixed.filter(x=>x.company===company&&x.start<=month).sort((a,b)=>b.start.localeCompare(a.start))[0];}
function tierCost(kwh:number, tiers:number[]){return Math.min(kwh,120)*tiers[0]+Math.max(Math.min(kwh-120,180),0)*tiers[1]+Math.max(kwh-300,0)*tiers[2];}
function sourceLabel(url:string){
  if(url.includes('tepco.co.jp/ep/private/fuelcost'))return 'TEPCO｜燃料費調整額';
  if(url.includes('tepco.co.jp/ep/private/plan'))return 'TEPCO｜基本・従量料金';
  if(url.includes('power-procurument'))return 'エネパル｜電源調達調整費';
  if(url.includes('area-price'))return 'エネパル｜基本・従量料金';
  return '公式資料';
}
function estimateEnepal(row:Usage,rates:Rates){const fixed=fixedFor(rates,'エネパル',row.month);const variable=rates.variable.find(v=>v.month===row.month);if(!fixed||!variable||variable.enepalProcurement==null||variable.renewable==null)return null;const m=Number(row.month.slice(5));const energy=(m>=7&&m<=9)?fixed.powerSummer:fixed.powerOther;const adjust=(variable.enepalFuel??0)+variable.enepalProcurement+(variable.support??0)+variable.renewable;return Math.floor(fixed.lightBase+tierCost(row.lighting,fixed.tiers)+row.lighting*adjust+fixed.stabilityLight+fixed.powerKw*fixed.powerBase+row.power*energy+row.power*adjust+fixed.stabilityPower);}

export default function Home(){
  const [rates,setRates]=useState<Rates>(initialRates); const [rows,setRows]=useState<Usage[]>([blankUsage]); const [active,setActive]=useState(0); const [ready,setReady]=useState(false); const fileRef=useRef<HTMLInputElement>(null);
  useEffect(()=>{Promise.resolve().then(()=>{const saved=localStorage.getItem('electricity-cost-compare:v1');if(saved){try{setRows(JSON.parse(saved) as Usage[]);}catch{}}});fetch('./data/rates.json').then(async r=>r.ok?await r.json() as Rates:null).then(x=>x&&setRates(x)).finally(()=>setReady(true));},[]);
  useEffect(()=>{if(ready)localStorage.setItem('electricity-cost-compare:v1',JSON.stringify(rows));},[rows,ready]);
  const row=rows[active]??blankUsage; const enepal=estimateEnepal(row,rates); const saving=enepal==null?null:row.actual-enepal; const variable=rates.variable.find(v=>v.month===row.month); const fixed=fixedFor(rates,'エネパル',row.month); const hasRecorded=rows.some(r=>r.lighting>0||r.power>0||r.actual>0);
  const annual=useMemo(()=>rows.reduce((sum,r)=>{const e=estimateEnepal(r,rates);return sum+(e==null?0:r.actual-e)},0),[rows,rates]);
  const update=(key:keyof Usage,value:string|number)=>setRows(prev=>prev.map((r,i)=>i===active?{...r,[key]:value}:r));
  const addMonth=()=>{if(rows.length>=12)return;const last=rows.at(-1)?.month??'2026-08';const d=new Date(`${last}-01T00:00:00`);d.setMonth(d.getMonth()+1);const month=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;setRows(prev=>[...prev,{...blankUsage,month,start:'',end:''}]);setActive(rows.length);};
  const deleteMonth=()=>{if(rows.length<=1||!window.confirm(`${row.month.replace('-','年')}月の記録を削除しますか？`))return;setRows(prev=>prev.filter((_,i)=>i!==active));setActive(Math.max(0,active-1));};
  const exportCsv=()=>{const body=['請求月,使用開始日,使用終了日,電灯kWh,動力kWh,TEPCO実請求額',...rows.map(r=>[r.month,r.start,r.end,r.lighting,r.power,r.actual].join(','))].join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\uFEFF'+body],{type:'text/csv'}));a.download='electricity-usage.csv';a.click();URL.revokeObjectURL(a.href);};
  const importCsv=(event:ChangeEvent<HTMLInputElement>)=>{const file=event.target.files?.[0];if(!file)return;file.text().then(text=>{const parsed=text.replace(/^\uFEFF/,'').trim().split(/\r?\n/).slice(1).map(line=>{const c=line.split(',');return{month:c[0],start:c[1],end:c[2],lighting:Number(c[3]),power:Number(c[4]),actual:Number(c[5])}}).filter(r=>/^\d{4}-\d{2}$/.test(r.month));if(parsed.length){setRows(parsed);setActive(0);}});event.target.value='';};
  const max=Math.max(1,...rows.map(r=>Math.max(r.actual,estimateEnepal(r,rates)??0)));
  return <main>
    <header className="site-header"><a className="brand" href="#top"><span className="brand-mark">E</span><span>電力契約の答え合わせ</span></a><nav><a href="#compare">比較</a><a href="#history">履歴</a><a href="#rates">料金データ</a></nav><span className="update-chip">公式データ更新 {rates.updatedAt.replaceAll('-','.')}</span></header>
    <section className="hero" id="top"><div><p className="eyebrow">TEPCO ACTUAL × ENEPAL IF</p><h1>東京電力に変えた判断は、<br/>正しかったか。</h1><p className="hero-copy">実際の東京電力の請求額と、エネパルを継続していた場合の推定額を毎月比較します。</p></div><div className="hero-note"><span>保存先</span><strong>この端末のみ</strong><p>入力内容は外部へ送信されません。CSVでバックアップできます。</p></div></section>
    <section className={`record-console ${hasRecorded?'returning':'first-use'}`}><div className="record-intro"><p>{hasRecorded?'MONTHLY UPDATE':'FIRST RECORD'}</p><h2>{hasRecorded?'新しい請求が届いたら':'最初の1か月を記録'}</h2><span>{hasRecorded?'月を追加して、使用量と東京電力の実請求額を入力します。':'請求書を見ながら、使用期間・使用量・実請求額を入力してください。'}</span></div><div className="month-board"><div className="month-board-head"><strong>記録月</strong><small>{rows.length} / 12か月</small></div><div className="month-grid">{rows.map((r,i)=><button className={i===active?'active':''} key={`${r.month}-${i}`} onClick={()=>setActive(i)}><span>{r.month.slice(0,4)}</span><b>{r.month.slice(5)}月</b></button>)}</div></div><div className="record-actions"><button className="primary-action" disabled={rows.length>=12} onClick={addMonth}>{rows.length>=12?'12か月記録済み':'＋ 次の月を追加'}</button><button className="delete-action" disabled={rows.length<=1} onClick={deleteMonth}>選択月を削除</button><div className="backup-actions"><button onClick={exportCsv}>CSV保存</button><button onClick={()=>fileRef.current?.click()}>CSV復元</button><input ref={fileRef} hidden type="file" accept=".csv,text/csv" onChange={importCsv}/></div></div></section>
    <section className="compare-layout" id="compare"><form className="input-panel" onSubmit={e=>e.preventDefault()}><div className="section-heading"><span>01</span><div><p>{row.month.replace('-','年')}月請求</p><h2>使用実績を入力</h2></div></div><label>請求月<span className="field"><input aria-label="請求月" type="month" value={row.month} onChange={e=>update('month',e.target.value)}/></span></label><label>使用期間<span className="date-pair"><input aria-label="使用開始日" type="date" value={row.start} onChange={e=>update('start',e.target.value)}/><b>—</b><input aria-label="使用終了日" type="date" value={row.end} onChange={e=>update('end',e.target.value)}/></span></label><label>電灯使用量<span className="field"><input aria-label="電灯使用量" type="number" min="0" value={row.lighting||''} onChange={e=>update('lighting',Number(e.target.value))}/><b>kWh</b></span></label><label>動力使用量<span className="field"><input aria-label="動力使用量" type="number" min="0" value={row.power||''} onChange={e=>update('power',Number(e.target.value))}/><b>kWh</b></span></label><label>TEPCO実請求額<span className="field"><input aria-label="TEPCO実請求額" type="number" min="0" value={row.actual||''} onChange={e=>update('actual',Number(e.target.value))}/><b>円</b></span></label><p className="form-note">入力内容は自動保存されます。</p></form>
    <div className="result-panel"><div className="section-heading light"><span>02</span><div><p>同じ使用実績で比較</p><h2>今月の結果</h2></div></div><div className="price-row"><span><i className="dot tepco"/>TEPCO 実請求</span><strong>{yen.format(row.actual)}</strong></div><div className="price-row"><span><i className="dot enepal"/>エネパル 推定</span><strong>{enepal==null?'公表待ち':yen.format(enepal)}</strong></div>{saving==null?<div className="verdict pending"><span>必要な調整単価が未公表です</span><strong>暫定</strong></div>:<div className={`verdict ${saving>=0?'positive':'negative'}`}><span>{saving>=0?'エネパルの方が安い推定':'TEPCOの方が安い'}</span><strong>{yen.format(Math.abs(saving))}</strong></div>}<p className="estimate-note">{fixed?.plan}</p></div></section>
    <section className="summary" id="history"><div><p>記録月数</p><strong>{rows.length}<small>か月</small></strong></div><div><p>年間累計差額</p><strong>{yen.format(Math.abs(annual))}</strong><span>{annual>=0?'エネパルが安い推定':'TEPCOが安い'}</span></div><div><p>データ状態</p><strong>{variable?.status??'未登録'}</strong></div></section>
    <section className="chart-card"><div className="section-heading"><span>03</span><div><p>月別支払額</p><h2>比較履歴</h2></div></div><div className="chart">{rows.map((r,i)=>{const e=estimateEnepal(r,rates);return <button key={i} onClick={()=>setActive(i)} className={i===active?'selected':''}><span className="bars"><i className="bar tepco-bar" style={{height:`${Math.max(2,r.actual/max*100)}%`}}/><i className="bar enepal-bar" style={{height:`${Math.max(2,(e??0)/max*100)}%`}}/></span><b>{r.month.slice(5)}月</b></button>})}</div><div className="legend"><span><i className="dot tepco"/>TEPCO実請求</span><span><i className="dot enepal"/>エネパル推定</span></div></section>
    <section className="rates" id="rates"><div className="section-heading"><span>04</span><div><p>監査可能な試算</p><h2>適用中の料金データ</h2></div></div><div className="rate-grid"><article><h3>TEPCO</h3><p>{fixedFor(rates,'TEPCO',row.month)?.plan}</p><dl><dt>燃料費調整</dt><dd>{variable?.tepcoFuel==null?'未公表':`${num.format(variable.tepcoFuel)}円/kWh`}</dd><dt>再エネ賦課金</dt><dd>{variable?.renewable==null?'未公表':`${num.format(variable.renewable)}円/kWh`}</dd></dl></article><article><h3>エネパル</h3><p>{fixed?.plan}</p><dl><dt>調達調整</dt><dd>{variable?.enepalProcurement==null?'公表待ち':`${num.format(variable.enepalProcurement)}円/kWh`}</dd><dt>国の支援</dt><dd>{variable?.support==null?'なし':`${num.format(variable.support)}円/kWh`}</dd></dl></article></div>
    <div className="history-block"><div className="history-title"><div><span>基本料金</span><h3>料金改定履歴</h3></div><small>契約容量を含む月額</small></div><div className="table-scroll"><table><thead><tr><th>適用開始</th><th>会社</th><th>電灯基本料金</th><th>動力基本料金</th><th>契約</th></tr></thead><tbody>{[...rates.fixed].sort((a,b)=>b.start.localeCompare(a.start)||a.company.localeCompare(b.company)).map((x,i)=><tr key={`${x.start}-${x.company}-${i}`}><td>{x.start.replace('-','年')}月</td><td><strong>{x.company}</strong></td><td>{yen.format(x.lightBase)}</td><td>{yen.format(x.powerBase*x.powerKw)}</td><td>{x.powerKw}kW</td></tr>)}</tbody></table></div></div>
    <div className="history-block"><div className="history-title"><div><span>月ごとの変動値</span><h3>調整額履歴</h3></div><small>1kWhあたり・税込</small></div><div className="table-scroll"><table><thead><tr><th>請求月</th><th>TEPCO 燃料費調整</th><th>エネパル 燃料費調整</th><th>エネパル 電源調達調整</th><th>状態</th></tr></thead><tbody>{[...rates.variable].sort((a,b)=>b.month.localeCompare(a.month)).map(x=><tr key={x.month}><td>{x.month.replace('-','年')}月</td><td>{x.tepcoFuel==null?'未公表':`${num.format(x.tepcoFuel)}円`}</td><td>{x.enepalFuel==null?'未公表':`${num.format(x.enepalFuel)}円`}</td><td>{x.enepalProcurement==null?<span className="waiting">公表待ち</span>:`${num.format(x.enepalProcurement)}円`}</td><td>{x.status}</td></tr>)}</tbody></table></div></div>
    <div className="sources">{[...(variable?.sources??[]),...(rates.fixed.map(x=>x.source))].filter((x,i,a)=>a.indexOf(x)===i).map(url=><a key={url} href={url} target="_blank" rel="noreferrer">{sourceLabel(url)} ↗</a>)}</div></section>
    <footer><p>公式単価に基づく試算です。日割り、力率、個別割引などにより実際の請求と異なる場合があります。</p><span>入力データはブラウザ内にのみ保存されます。</span></footer>
  </main>;
}

